### ISSUE TITLE
IfcBsplineSurfaceWithKnots: Twodimensional lists of entities

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/BIMserver#1053]
Twodimensional lists of entities seem not to be properly treated in the JSON Serializer (runtime exception) and query for render engine processing (omission).

To reproduce, use the [IfcAdvancedBrep basin example](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/annex/annex-e/basin-advanced-brep.ifc) from buildingsmart and check in with BIMserver, geometry generation enabled.

Use the JSON Serializer to download the file or alternatively navigate to any IfcBSplineSurfaceWithKnots in bimvie.ws entity browser. You'll see the following error:

    14:40:25 ERROR [qtp967531000-40]:  (DownloadServlet.java:255) 
    org.bimserver.plugins.serializers.SerializerException: java.lang.ClassCastException: java.lang.Long cannot be cast to org.bimserver.shared.MinimalVirtualObject
        at org.bimserver.emf.SharedJsonStreamingSerializer.write(SharedJsonStreamingSerializer.java:131)
        at org.bimserver.emf.SharedJsonStreamingSerializer.write(SharedJsonStreamingSerializer.java:454)
        at org.bimserver.serializers.StreamingJsonSerializer.writeToOutputStream(StreamingJsonSerializer.java:52)
        at org.bimserver.plugins.serializers.StreamingSerializerDataSource.writeToOutputStream(StreamingSerializerDataSource.java:67)
        at org.bimserver.servlets.DownloadServlet.processDataSource(DownloadServlet.java:288)
        at org.bimserver.servlets.DownloadServlet.service(DownloadServlet.java:249)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:155)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:505)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to org.bimserver.shared.MinimalVirtualObject
        at org.bimserver.emf.SharedJsonStreamingSerializer.write(SharedJsonStreamingSerializer.java:330)
        at org.bimserver.emf.SharedJsonStreamingSerializer.writeObject(SharedJsonStreamingSerializer.java:222)
        at org.bimserver.emf.SharedJsonStreamingSerializer.write(SharedJsonStreamingSerializer.java:116)
        ... 40 common frames omitted

Now look at the geometry generation report. The same file also causes [issues in IfcOpenShell](https://github.com/IfcOpenShell/IfcOpenShell/issues/586). But already the IFC passed to the render engine is erroneous. The debug files contain these lines:

    #77= IFCBSPLINESURFACEWITHKNOTS(3,3,((),(),(),()),...);
    #78= IFCBSPLINESURFACEWITHKNOTS(3,3,((),(),(),()),...);

The original IFC had references to `IfcCartesianPoint` entities in those twodimensional arrays:

    #548= IFCBSPLINESURFACEWITHKNOTS(3,3,((#549,#550,#551,#552,#549,#550,#551),(#553,#554,#555,#556,#553,#554,#555),(#557,#558,#559,#560,#557,#558,#559),(#561,#562,#563,#564,#561,#562,#563)),...);
    #572= IFCBSPLINESURFACEWITHKNOTS(3,3,((#573,#574,#575,#576,#573,#574,#575),(#577,#578,#579,#580,#577,#578,#579),(#581,#582,#583,#584,#581,#582,#583),(#585,#586,#587,#588,#585,#586,#587)),...);

The roundtrip using the streamed IFC4 serializer for full download of the revision works fine, so the deserailization and storage in database should be fine.

This was observerd with BIMserver 1.5.162.

**Comment by rubendel** [comment]
**JSON Serializer**
This specific JSON serialization error was actually solved in https://github.com/opensourceBIM/BIMserver/commit/fb5eef16699cdb17c0648603481b1a24979b9d7b, so that's after 1.5.162 was made available.

Testing with BIMvie.ws however resulted in incorrect results, those are fixed now too (https://github.com/opensourceBIM/BIMserver/commit/e519f6c0afd586148018742747e8a2a24a620be1).

**IFC Serializer**
This I can reproduce in BIMserver HEAD, will have a look at that later.

**Comment by rubendel** [comment]
IFC Serializer is fixed now too. Would be nice to have more test files with these types. I tried opening this `basin-advanced-brep.ifc` example in all the viewers I have installed, none of them showed anything. Also I don't think IfcOpenShell supports this type of geometry yet, but supporting it in BIMserver is a first step I guess :).

IfcOpenShell output (of the original file):
```
IfcOpenShell IfcConvert 0.6.0a1 (OCC 7.3.0)
Scanning file...
Done scanning file
Parsing input file took 0 seconds

Log:
[Error] {0dOOwKTsn8I8gwbP3LM1Yz} Unknown error creating face
[Error] {0dOOwKTsn8I8gwbP3LM1Yz} Unknown error creating face
[Error] {0dOOwKTsn8I8gwbP3LM1Yz} Unknown error creating face
[Error] {0dOOwKTsn8I8gwbP3LM1Yz} Unknown error creating face
[Error] {0dOOwKTsn8I8gwbP3LM1Yz} Unknown error creating face
[Error] {0dOOwKTsn8I8gwbP3LM1Yz} Failed to convert:
#611=IfcClosedShell((#565,#589,#595,#601,#610))
```

**Comment by hlg** [comment]
Confirming it works now.

I think adoption will very much depend on whether this is included in the "Design Transfer View" MVD and thus covered by the certification process, otherwise no-one will implement it. But I still don't find any official DTV release. At least BIMserver is not in the way.

Yes, there is some work going on with IfcOpenShell, but the issues seem to go all the way down to OCCT: https://github.com/IfcOpenShell/IfcOpenShell/issues/586#issuecomment-549855992.
