### ISSUE TITLE
Bimsie1LowLevelInterface.removeReference problem

### ISSUE THREAD

**Issue by dlabz** [opensourceBIM/BIMserver#193]
Calling Bimsie1LowLevelInterface.commitTransaction after Bimsie1LowLevelInterface.removeReference will return error.

```
ERROR                                                                                  (org.bimserver.JsonHandler.java:149) 
java.lang.NullPointerException
	at org.eclipse.emf.common.util.AbstractEList.getNonDuplicates(AbstractEList.java:1161)
	at org.eclipse.emf.common.util.AbstractEList.addAll(AbstractEList.java:366)
	at org.eclipse.emf.ecore.util.EcoreEList.set(EcoreEList.java:457)
	at org.eclipse.emf.ecore.impl.EStructuralFeatureImpl$InternalSettingDelegateMany.dynamicSet(EStructuralFeatureImpl.java:1729)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eDynamicSet(BasicEObjectImpl.java:1127)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet(BasicEObjectImpl.java:1101)
	at org.bimserver.emf.IdEObjectImpl.eSet(IdEObjectImpl.java:213)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet(BasicEObjectImpl.java:1071)
	at org.bimserver.emf.IdEObjectImpl.eSet(IdEObjectImpl.java:89)
	at org.bimserver.changes.RemoveReferenceChange.execute(RemoveReferenceChange.java:70)
	at org.bimserver.database.actions.CommitTransactionDatabaseAction.execute(CommitTransactionDatabaseAction.java:158)
	at org.bimserver.database.actions.CommitTransactionDatabaseAction.execute(CommitTransactionDatabaseAction.java:57)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:602)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:594)
	at org.bimserver.webservices.impl.Bimsie1LowLevelServiceImpl.commitTransaction(Bimsie1LowLevelServiceImpl.java:109)
	at org.bimserver.generated.Bimsie1LowLevelInterfaceReflector1.callMethod(Bimsie1LowLevelInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:219)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:124)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:98)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

Ubuntu 14.10 x64, tomcat7
bimserver-tomcat7-1.4.0-FINAL-2015-03-10.war

**Comment by rubendel** [comment]
I have fixed all the unit tests, removeReference was also not working (but got another exception). Can you try again and if it's not working provide the code you are using?

**Comment by dlabz** [comment]
I pulled the master from the git to test...

The console.html isn't working (again) to test directly on the api, so I used bimserverapi.js, and it threw the same error.

What I'm trying to achieve is remove an object from a group.
I get the IfcRelAssignsToGroup object, and try to remove an object from it's RelatedObjects multi-reference by calling Bimsie1LowLevelInterface.removeReference

If you need more info, I can send the IFC file and a javascript file that would illustrate the issue.

**Comment by dlabz** [comment]
Took another look in this issue. Turns out my local git clone was corrupted, so now console.html is working, although it still logs some errors in java console:
```
11:35:31 ERROR Invocation without a binding operation.                                          11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:30 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:31 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:31 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:31 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
11:35:31 ERROR Invocation without a binding operation.                                          (org.apache.cxf.service.invoker.AbstractInvoker.java:58) 
```
and js console:
```
Uncaught SyntaxError: Unexpected token <
jquery-2.1.0.min.js:4 Resource interpreted as Script but transferred with MIME type text/xml: "http://localhost:8080/soap11/AuthInterface?js&_=1427366313672".
ServiceInterface?js&_=1427366313673:1 Uncaught SyntaxError: Unexpected token <
AdminInterface?js&_=1427366313674:1 Uncaught SyntaxError: Unexpected token <
MetaInterface?js&_=1427366313675:1 Uncaught SyntaxError: Unexpected token <
PluginInterface?js&_=1427366313676:1 Uncaught SyntaxError: Unexpected token <
jquery-2.1.0.min.js:4 Resource interpreted as Script but transferred with MIME type text/xml: "http://localhost:8080/soap11/ServiceInterface?js&_=1427366313673".
jquery-2.1.0.min.js:4 Resource interpreted as Script but transferred with MIME type text/xml: "http://localhost:8080/soap11/AdminInterface?js&_=1427366313674".
jquery-2.1.0.min.js:4 Resource interpreted as Script but transferred with MIME type text/xml: "http://localhost:8080/soap11/MetaInterface?js&_=1427366313675".
jquery-2.1.0.min.js:4 Resource interpreted as Script but transferred with MIME type text/xml: "http://localhost:8080/soap11/PluginInterface?js&_=1427366313676".
SettingsInterface?js&_=1427366313677:1 Uncaught SyntaxError: Unexpected token <
Bimsie1NotificationRegistryInterface?js&_=1427366313678:1 Uncaught SyntaxError: Unexpected token <
Bimsie1RemoteServiceInterface?js&_=1427366313679:1 Uncaught SyntaxError: Unexpected token <
jquery-2.1.0.min.js:4 Resource interpreted as Script but transferred with MIME type text/xml: "http://localhost:8080/soap11/SettingsInterface?js&_=1427366313677".jquery-2.1.0.min.js:4 o.ajaxTransport.sendjquery-2.1.0.min.js:4 o.extend.ajaxjquery-2.1.0.min.js:4 o.each.o.(anonymous function)jquery-2.1.0.min.js:4 o.extend.getScriptconsole.html:811 (anonymous function)consolesettings.js:9 (anonymous function)jquery-2.1.0.min.js:2 o.Callbacks.jjquery-2.1.0.min.js:2 o.Callbacks.k.fireWithjquery-2.1.0.min.js:4 xjquery-2.1.0.min.js:4 o.ajaxTransport.l.cors.a.crossDomain.send.b
jquery-2.1.0.min.js:4 Resource interpreted as Script but transferred with MIME type text/xml: "http://localhost:8080/soap11/Bimsie1NotificationRegistryInterface?js&_=1427366313678".
Bimsie1AuthInterface?js&_=1427366313680:1 Uncaught SyntaxError: Unexpected token <
jquery-2.1.0.min.js:4 Resource interpreted as Script but transferred with MIME type text/xml: "http://localhost:8080/soap11/Bimsie1RemoteServiceInterface?js&_=1427366313679".
jquery-2.1.0.min.js:4 Resource interpreted as Script but transferred with MIME type text/xml: "http://localhost:8080/soap11/Bimsie1AuthInterface?js&_=1427366313680".
Bimsie1ServiceInterface?js&_=1427366313681:1 Uncaught SyntaxError: Unexpected token <
Bimsie1LowLevelInterface?js&_=1427366313682:1 Uncaught SyntaxError: Unexpected token <
jquery-2.1.0.min.js:4 Resource interpreted as Script but transferred with MIME type text/xml: "http://localhost:8080/soap11/Bimsie1ServiceInterface?js&_=1427366313681".
Bimsie1NotificationInterface?js&_=1427366313683:1 Uncaught SyntaxError: Unexpected token <
jquery-2.1.0.min.js:4 Resource interpreted as Script but transferred with MIME type text/xml: "http://localhost:8080/soap11/Bimsie1LowLevelInterface?js&_=1427366313682".
jquery-2.1.0.min.js:4 Resource interpreted as Script but transferred with MIME type text/xml: "http://localhost:8080/soap11/Bimsie1NotificationInterface?js&_=1427366313683".
```
calling the functions to start transaction:
```
{"token":"396beed81964da296ed87f4e8edd7165d8450ede84f23dbba3d29def8d74036bf9751a79ea739fea8fa7f4770884e841","request":{"interface":"Bimsie1LowLevelInterface","method":"startTransaction","parameters":{"poid":"131073"}}}
```
remove reference
```
{"token":"396beed81964da296ed87f4e8edd7165d8450ede84f23dbba3d29def8d74036bf9751a79ea739fea8fa7f4770884e841","request":{"interface":"Bimsie1LowLevelInterface","method":"removeReference","parameters":{"tid":"4","oid":"197158","referenceName":"RelatedObjects","index":"0"}}}
```

and commit
```
{"token":"396beed81964da296ed87f4e8edd7165d8450ede84f23dbba3d29def8d74036bf9751a79ea739fea8fa7f4770884e841","request":{"interface":"Bimsie1LowLevelInterface","method":"commitTransaction","parameters":{"tid":"4","comment":"remove"}}}
```

will give following error in java console, in eclipse
```
11:46:24 ERROR                                                                                  (org.bimserver.JsonHandler.java:149) 
java.lang.NullPointerException
	at org.eclipse.emf.common.util.AbstractEList.getNonDuplicates(AbstractEList.java:1161)
	at org.eclipse.emf.common.util.AbstractEList.addAll(AbstractEList.java:366)
	at org.eclipse.emf.ecore.util.EcoreEList.set(EcoreEList.java:457)
	at org.eclipse.emf.ecore.impl.EStructuralFeatureImpl$InternalSettingDelegateMany.dynamicSet(EStructuralFeatureImpl.java:1729)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eDynamicSet(BasicEObjectImpl.java:1127)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet(BasicEObjectImpl.java:1101)
	at org.bimserver.emf.IdEObjectImpl.eSet(IdEObjectImpl.java:191)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet(BasicEObjectImpl.java:1071)
	at org.bimserver.emf.IdEObjectImpl.eSet(IdEObjectImpl.java:70)
	at org.bimserver.changes.RemoveReferenceChange.execute(RemoveReferenceChange.java:70)
	at org.bimserver.database.actions.CommitTransactionDatabaseAction.execute(CommitTransactionDatabaseAction.java:158)
	at org.bimserver.database.actions.CommitTransactionDatabaseAction.execute(CommitTransactionDatabaseAction.java:1)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:601)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:593)
	at org.bimserver.webservices.impl.Bimsie1LowLevelServiceImpl.commitTransaction(Bimsie1LowLevelServiceImpl.java:109)
	at org.bimserver.generated.Bimsie1LowLevelInterfaceReflector1.callMethod(Bimsie1LowLevelInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:219)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:124)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:98)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rubendel** [comment]
Unit tests calling removeReference are running fine, this is quite an old issue, is it still an issue?

**Comment by dlabz** [comment]
Still an issue.
After the last update of BIMserver, I deleted home folder, set up BIMserver again, checked in IfcOpenHouse.ifc, and tried number of modifications to the model, all resulting in a BimServer database exemption:
```
08-08-2015 19:19:21 INFO  Inefficient getMap                                                               (org.bimserver.database.DatabaseSession.java:1097) 
08-08-2015 19:19:21 INFO  Initializing IfcOpenShell engine                                                 (org.ifcopenshell.IfcOpenShellEngine.java:52) 
08-08-2015 19:19:22 INFO  Took 1.08 seconds to obtain representations for 39 entities                      (org.ifcopenshell.IfcOpenShellModel.java:85) 
08-08-2015 19:19:22 INFO  Closing IfcOpenShell engine                                                      (org.ifcopenshell.IfcOpenShellEngine.java:57) 
08-08-2015 19:19:22 INFO  Rendertime: 1131ms, Reused:     26.63 KB, Total:    126.33 KB, Final:     99.70 KB (org.bimserver.GeometryGenerator.java:431) 
08-08-2015 19:19:22 ERROR                                                                                  (org.bimserver.webservices.impl.Bimsie1LowLevelServiceImpl.java:112) 
org.bimserver.database.BimserverDatabaseException: Writing a reference with oid -1, this is not supposed to happen, referenced: -1 org.bimserver.models.geometry.impl.GeometryInfoImpl@6e815881 from 65964 org.bimserver.models.ifc2x3tc1.impl.IfcMemberImpl@72b82ddb
	at org.bimserver.database.DatabaseSession.writeReference(DatabaseSession.java:1744)
	at org.bimserver.database.DatabaseSession.convertObjectToByteArray(DatabaseSession.java:483)
	at org.bimserver.database.DatabaseSession.commit(DatabaseSession.java:188)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:595)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:585)
	at org.bimserver.webservices.impl.Bimsie1LowLevelServiceImpl.commitTransaction(Bimsie1LowLevelServiceImpl.java:109)
	at org.bimserver.generated.Bimsie1LowLevelInterfaceReflector1.callMethod(Bimsie1LowLevelInterfaceReflector1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:219)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:126)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:73)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:105)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rubendel** [comment]
This is a completely different error message, happening on a different call
