### ISSUE TITLE
org.bimserver.shared.exceptions.ServerException: java.nio.BufferOverflowException when commitTransaction

### ISSUE THREAD

**Issue by RoudautTanguy** [opensourceBIM/BIMserver#740]
Hello, i want to update some properties of an object so I use 
> bimServerClient.getLowLevelInterface().setStringAttribute(tid, object.getOid(), "GlobalId", "GUID123455"); 

such as the example in https://github.com/opensourceBIM/BIMserver/wiki/Low-Level-Calls . 
I have the following error in my console.
`org.bimserver.shared.exceptions.ServerException: java.nio.BufferOverflowException
at org.bimserver.shared.json.JsonReflector.callMethod(JsonReflector.java:84)
	at org.bimserver.generated.LowLevelInterfaceImpl1.commitTransaction(LowLevelInterfaceImpl1.java)
	at bimserver.UpdateProject.main(UpdateProject.java:166)`

So this is my line 166 : 
> Long newRoid  = bimServerClient.getLowLevelInterface().commitTransaction(tid, "update Properties");

Is this the good way to update propeties of an IfcObject to see the change in BIMvie.ws ?
I also try to use : 
  

>  IfcBoolean bool = (IfcBoolean) project.model.create(IfcBoolean.class);
>    bool.setWrappedValue(Tristate.TRUE);
>    ifcPSV.setNominalValue(bool);

but it also doesn't work.
I use the version 1.5.95.

**Comment by rubendel** [comment]
I am not able to reproduce this, but those errors should never happen. Can you maybe post your full code? The pieces posted seem fine.

**Comment by RoudautTanguy** [comment]
In fact it's just when I use 
      `bimServerClient.getLowLevelInterface().setWrappedDoubleAttribute(mainview.model.tid, ifcPSV.getOid(), "NominalValue", "IfcLengthMeasure", 1.2);`

I have no problems for setting wrapped String/Long/Boolean Attributes but when it's a real it can't update the property and I have this error.

**Comment by rubendel** [comment]
Ah ok originally you mentioned that you were setting a _boolean value_. I could indeed reproduce setting a _real/double_ value. This has now been fixed in GIT and a unit test has been added.

**Comment by RoudautTanguy** [comment]
I copy/paste your https://github.com/opensourceBIM/BIMserver/blob/e4fe8e6823a2519aa35bb9741c6645f1f387df8d/Tests/test/org/bimserver/tests/lowlevel/TestSetWrappedReal.java and I changed the bimServerClient to connect to my BIMServer and I still have the same error ...

`org.bimserver.shared.exceptions.ServerException: java.nio.BufferOverflowException
	at org.bimserver.shared.json.JsonReflector.callMethod(JsonReflector.java:84)
	at org.bimserver.generated.LowLevelInterfaceImpl1.commitTransaction(LowLevelInterfaceImpl1.java)
	at bimserver.UpdateTest.main(UpdateTest.java:44)`

Thanks anyway for your answer

**Comment by rubendel** [comment]
Just to check, you also updated your BIMserver to the latest version in GIT?

**Comment by RoudautTanguy** [comment]
I use the 1.5.95 version and I try with the 1.5.101 version but still have this issue

**Comment by rubendel** [comment]
How could a change done 4 hours ago show up in a release from weeks ago?

**Comment by RoudautTanguy** [comment]
I just downloaded the latest version on the release page. 
I don't know how to run the latest version from a zip.

**Comment by rubendel** [comment]
It says "released this 21 days ago". So you'll have to wait for a new release.
