### ISSUE TITLE
BIMServer1.5.x - Plugin Installation problem - 

### ISSUE THREAD

**Issue by Elsa-E4-user** [opensourceBIM/BIMserver#753]
BIMVersion:BIMServer1.5.100
Tested also with BIMServer1.5.95 (same issue)

When installing plugins the following appear in the setup window [see also attached picture]:

Installing plugins...
		Installing bimsurfer...
		Plugin bundle already installed org.opensourcebim.bimsurfer
		Installing bimviews...
		Plugin bundle already installed org.opensourcebim.bimviews
		Installing ifcopenshellplugin...
		Plugin bundle already installed org.opensourcebim.ifcopenshellplugin
		Installing ifcplugins...
		Plugin bundle already installed org.opensourcebim.ifcplugins
		Installing binaryserializers...
		Plugin bundle already installed org.opensourcebim.binaryserializers
		Installing bimserverapi...
		Plugin bundle already installed org.opensourcebim.bimserverapi
		Installing console...
		Plugin bundle already installed org.opensourcebim.console
		All remote plugins successfully installed

Setup successful, refresh to go to the status page

When refreshing the page no web module is available.

In the WEB-INF folder the following has been created:
	maven/org/bimserver
with the following folders:
	- bimsurfer
	- bimviews
	- ifcopenshellplugin
	- ifcplugins
	- binaryserializers
	- bimserverapi
	- console

each folder has a unique file inside named:
	- resolver-status.properties
all the files has the same content except for the name [replaced with <<cur_dir_name>> hereafter]:
	#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
	#Mon May 07 16:45:47 CEST 2018
	maven-metadata-central.xml/@default-central-http\://central.maven.org/maven2/.lastUpdated=1525704337125
	maven-metadata-local.xml.lastUpdated=1525704327114
	maven-metadata-central.xml.error=Could not transfer metadata org.opensourcebim\:<<cur_dir_name>>/maven-metadata.xml from/to central (ht
	tp\://central.maven.org/maven2)\: Connect to central.maven.org\:80 timed out
	maven-metadata-given.xml.error=Could not transfer metadata org.opensourcebim\:bimserverapi/maven-metadata.xml from/to given (http\:
	//central.maven.org/maven2)\: Connect to central.maven.org\:80 timed out
	maven-metadata-github.xml/@default-github-http\://repo.logic-labs.nl.s3.amazonaws.com/release/.lastUpdated=1525704337154
	maven-metadata-given.xml/@default-given-http\://central.maven.org/maven2/.lastUpdated=1525704347168
	maven-metadata-local.xml.error=
	maven-metadata-github.xml.error=Could not transfer metadata org.opensourcebim\:<<cur_dir_name>>/maven-metadata.xml from/to github (http
	\://repo.logic-labs.nl.s3.amazonaws.com/release)\: Connect to repo.logic-labs.nl.s3.amazonaws.com\:80 timed out

In the bimserver logfile the only message logged durign the setup is the following:
 [AdminInterface.setup] o.b.ServerInfoManager [ServerInfoManager.java:96] Changing server state to RUNNING
 
![bimserver100failuretrackedassuccess](https://user-images.githubusercontent.com/34245289/39710369-e901dd2a-521c-11e8-9127-43a502f57356.jpg)

Found exception in jetty console stderr/stdout  log file:

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('{' (code 123)): was expecting double-quote to start field name
 at [Source: (String)"{
  "plugins": [{
    "maven": {
      "defaultrepository": "http://central.maven.org/maven2",
      "groupId": "org.opensourcebim",
      "artifactId": "binaryserializers"
    }
  }, {
    "maven": {
      "defaultrepository": "http://central.maven.org/maven2",
      "groupId": "org.opensourcebim",
      "artifactId": "ifcopenshellplugin"
    }
  }, {
    "maven": {
      "defaultrepository": "http://central.maven.org/maven2",
      "groupId": "org.opensourcebim",
      "artifactId": "javamodel"[truncated 3230 chars]; line: 133, column: 7]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1757)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:907)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:247)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:434)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer$ObjectDeserializer.deserialize(JsonNodeDeserializer.java:97)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer$ObjectDeserializer.deserialize(JsonNodeDeserializer.java:82)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
        at org.bimserver.plugins.GitHubPluginRepository.listPluginLocations(GitHubPluginRepository.java:56)
        at org.bimserver.database.actions.GetInstalledPluginBundles.execute(GetInstalledPluginBundles.java:68)
        at org.bimserver.database.actions.GetInstalledPluginBundles.execute(GetInstalledPluginBundles.java:47)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:726)
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:718)
        at org.bimserver.webservices.impl.PluginServiceImpl.getInstalledPluginBundles(PluginServiceImpl.java:1529)
        at org.bimserver.generated.PluginInterfaceReflector1.callMethod(PluginInterfaceReflector1.java)
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213)
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:148)
        at org.bimserver.JsonHandler.execute(JsonHandler.java:64)
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70)
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:530)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Thread.java:748)

**Comment by rubendel** [comment]
I think there are two problems. The message "Connect to central.maven.org:80 timed out" indicates that either maven central was out for a while, or some firewall is blocking access to that address.

The other problem is that the JSON file at https://github.com/opensourceBIM/BIMserver-Repository/blob/master/plugins.json was invalid, that's fixed now, so the same releases should work (could take a while for github cache to update btw).

**Comment by Elsa-E4-user** [comment]
Dear Ruben, thank for your answer, as by your expectation fixing the syntax error doesn't solve the connection problem.
Following some Questions and further info for analysis.
- To check our service proxy behavior I tried a "wget" locally and it seems that currently the URL http://central.maven.org/maven2 is redirect. could this be the cause of the error?
- Is it possible to have more diagnostic in the plugins installation?
- Do you have a list of used repo domain to be able to ask to our proxy service to open access to?
- Manual installation bring to a situation similar to the one detected in https://github.com/opensourceBIM/BIMserver/issues/745, is it possible to fix manually the plugins installation?  
I traced the network connection and I'm going to attach the trace and all the other information to this comment. (there are some SIGSEGV in the trace but I couldn't find exception in the logs)
  
AddInfoStracing-1.5.100.txt gives detailed info on env and test steps.
JETTY-20616 is the network tracing during the installation

[AddInfoStracing-1.5.100.txt](https://github.com/opensourceBIM/BIMserver/files/2009425/AddInfoStracing-1.5.100.txt)
[JETTY-20616.txt](https://github.com/opensourceBIM/BIMserver/files/2009584/JETTY-20616.txt)

[2018_05_16.jetty.log](https://github.com/opensourceBIM/BIMserver/files/2009636/2018_05_16.jetty.log)
[bimserver.log](https://github.com/opensourceBIM/BIMserver/files/2009656/bimserver.log)

[bimviews-resolver-status.properties.txt](https://github.com/opensourceBIM/BIMserver/files/2009664/bimviews-resolver-status.properties.txt)
[bimsurfer-resolver-status.properties.txt](https://github.com/opensourceBIM/BIMserver/files/2009665/bimsurfer-resolver-status.properties.txt)
[WEB-INF_bimserver.log](https://github.com/opensourceBIM/BIMserver/files/2009670/WEB-INF_bimserver.log)

**Comment by rubendel** [comment]
Sorry for the late reply.

The http://central.maven.org/maven2 url does not redirect here, so that's probably indeed your annoying firewall/proxy, ask your sysadmin to fix this, there is absolutely no reason to redirect every single http request.

Over time more diagnostics will probably be added, supporting proxies however will probably never be something I enjoy spending time on.

I have no such list, basically every plugin can use their own URL.
